rvm:
- 2.1

sudo: true

env:
  matrix:
  - TESTS="style unit" CHEF_VERSION="~> 12.0"

bundler_args: --jobs=3 --retry=3 --without='doc integration_vagrant integration_cloud guard'

before_script:
- source <(curl -sL https://raw.githubusercontent.com/floored1585/quagga-cookbook/master/scripts/start_docker.sh)

script:
- travis_retry bundle exec rake integration:docker

after_failure: cat docker_daemon.log
